# https://starship.rs/config
add_newline = false
command_timeout = 1000
scan_timeout = 50
continuation_prompt = ">>"

[character]
success_symbol = "[>](bold white)"
error_symbol = "[>](bold red)"

[line_break]
disabled = true

[status]
disabled = false
format = "[$status]($style) "

[shell]
disabled = false
zsh_indicator = ''
bash_indicator = 'bash '
format = '[$indicator]($style)'

[shlvl]
disabled = false
format = '[$symbol]($style) '
style = 'bold bright-yellow'
symbol = 'âŸ©'
repeat = true
repeat_offset = 1
threshold = 2

[cmd_duration]
format = "[took $duration]($style) "
#show_notifications = true
#min_time_to_notify = 5000

[directory]
truncate_to_repo = false
style = "white"
read_only = " ó°Œ¾"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ï˜ "
format = "[\\([$symbol$branch](green)\\)](purple)"
only_attached = true
[git_commit]
format= "[\\([$hash](green)\\)](purple) "
[git_status]
format = "([\\[$all_status$ahead_behind\\]](purple)) "
stashed = "[$](bold orange)"
renamed = "[Â»](bold blue)"
deleted = "[âœ˜](bold red)"
staged = "[+](bold green)"
conflicted = "[âœ–](red)"
modified = "[â—](bold blue)"
behind = "[â‡£$count](bold white)"
ahead = "[â‡¡$count](bold white)"
diverged = "[â‡•$count](bold white)"
untracked = "[?](bold yellow)"

[hostname]
disabled = true
ssh_symbol = "î¬ "

[username]
format = "[$user]($style) "

### nerd font symbols ###
### https://starship.rs/presets/nerd-font
### No Runtimes Versions Format ###
### https://starship.rs/presets/no-runtimes
[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[aws]
symbol = "îŒ½  "
[buf]
symbol = "ï’ "
format = "via [$symbol]($style)"
[bun]
format = "via [$symbol]($style)"
[c]
symbol = "î˜ "
[cmake]
format = "via [$symbol]($style)"
[cobol]
format = "via [$symbol]($style)"
[conda]
symbol = "ï„Œ "
[crystal]
symbol = "î˜¯ "
format = "via [$symbol]($style)"
[daml]
format = "via [$symbol]($style)"
[dart]
symbol = "î˜ "
format = "via [$symbol]($style)"
[deno]
format = "via [$symbol]($style)"
# [directory]
# read_only = " ó°Œ¾"
[docker_context]
symbol = "ïŒˆ "
[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"
[elixir]
symbol = "î˜­ "
format = "via [$symbol]($style)"
[elm]
symbol = "î˜¬ "
format = "via [$symbol]($style)"
[erlang]
format = "via [$symbol]($style)"
[fennel]
symbol = "îš¯ "
format = "via [$symbol]($style)"
[fossil_branch]
symbol = "ï˜ "
# [git_branch]
# symbol = "ï˜ "
[gleam]
format = "via [$symbol]($style)"
[golang]
symbol = "î˜§ "
format = "via [$symbol]($style)"
[gradle]
format = "via [$symbol]($style)"
[guix_shell]
symbol = "ïŒ¥ "
[haskell]
symbol = "î· "
[haxe]
symbol = "î™¦ "
format = "via [$symbol]($style)"
[helm]
format = "via [$symbol]($style)"
[hg_branch]
symbol = "ï˜ "
# [hostname]
# ssh_symbol = "î¬ "
[java]
symbol = "î‰– "
format = "via [$symbol]($style)"
[julia]
symbol = "î˜¤ "
format = "via [$symbol]($style)"
[kotlin]
symbol = "î˜´ "
format = "via [$symbol]($style)"
[lua]
symbol = "î˜  "
format = "via [$symbol]($style)"
[memory_usage]
symbol = "ó°› "
[meson]
symbol = "ó°”· "
format = "via [$symbol]($style)"
[nim]
symbol = "ó°†¥ "
format = "via [$symbol]($style)"
[nix_shell]
symbol = "ïŒ“ "
[nodejs]
symbol = "îœ˜ "
format = "via [$symbol]($style)"
[ocaml]
symbol = "î™º "
format = "via [$symbol]($style)"
[opa]
format = "via [$symbol]($style)"
[package]
symbol = "ó°— "
[perl]
symbol = "î™¾ "
format = "via [$symbol]($style)"
[php]
symbol = "î˜ˆ "
format = "via [$symbol]($style)"
[pijul_channel]
symbol = "ï˜ "
[pulumi]
format = "via [$symbol$stack]($style)"
[purescript]
format = "via [$symbol]($style)"
[python]
symbol = "îˆµ "
format = "via [$symbol]($style)"
[quarto]
format = "via [$symbol]($style)"
[raku]
format = "via [$symbol]($style)"
[red]
format = "via [$symbol]($style)"
[rlang]
symbol = "ó°Ÿ” "
format = "via [$symbol]($style)"
[ruby]
symbol = "î‘ "
format = "via [$symbol]($style)"
[rust]
symbol = "ó±˜— "
format = "via [$symbol]($style)"
[scala]
symbol = "îœ· "
[solidity]
format = "via [$symbol]($style)"
[swift]
symbol = "î• "
format = "via [$symbol]($style)"
[typst]
format = "via [$symbol]($style)"
[vagrant]
format = "via [$symbol]($style)"
[vlang]
format = "via [$symbol]($style)"
[zig]
symbol = "îš© "
format = "via [$symbol]($style)"
