# https://starship.rs/config
add_newline = false
command_timeout = 1000
scan_timeout = 50
continuation_prompt = ">>"

[character]
success_symbol = "[>](bold white)"
error_symbol = "[>](bold red)"

[line_break]
disabled = true

[status]
disabled = false
format = "[$status]($style)"

[cmd_duration]
format = "[took $duration]($style) "
#show_notifications = true
#min_time_to_notify = 5000

[directory]
truncate_to_repo = false
style = "white"
read_only = " ï ½"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ï˜ "
format = "[\\([$symbol$branch](green)\\)](purple)"
only_attached = true
[git_commit]
format= "[\\([$hash](green)\\)](purple) "
[git_status]
format = "([\\[$all_status$ahead_behind\\]](purple)) "
stashed = "[$](bold orange)"
renamed = "[Â»](bold blue)"
deleted = "[âœ˜](bold red)"
staged = "[+](bold green)"
conflicted = "[âœ–](red)"
modified = "[â—](bold blue)"
behind = "[â‡£$count](bold white)"
ahead = "[â‡¡$count](bold white)"
diverged = "[â‡•$count](bold white)"
untracked = "[?](bold yellow)"

[hg_branch]
symbol = "ï˜ "

[memory_usage]
symbol = "ï¡š "

[hostname]
disabled = true

[username]
format = "[$user]($style) "

### Symbol config ###
[aws]
symbol = "îŒ½  "
format = 'via [$symbol]($style)'
[buf]
symbol = "ï’ "
format = "via [$symbol]($style)"
[c]
symbol = "î˜ "
format = 'via [$symbol]($style)'
[cmake]
format = "via [$symbol]($style)"
[conda]
symbol = "ï„Œ "
format = 'via [$symbol]($style)'
[crystal]
format = "via [$symbol]($style)"
[dart]
symbol = "î˜ "
format = "via [$symbol]($style)"
[deno]
format = "via [$symbol]($style)"
[docker_context]
symbol = "ïŒˆ "
format = 'via [$symbol]($style)'
[dotnet]
symbol = "î¿ "
format = "[$symbol(ğŸ¯ $tfm )]($style)"
[elixir]
symbol = "î‰µ "
format = 'via [$symbol]($style)'
[elm]
symbol = "î˜¬ "
format = 'via [$symbol]($style)'
[erlang]
symbol = "î± "
format = 'via [$symbol]($style)'
[golang]
symbol = "î˜§ "
format = 'via [$symbol]($style)'
[haskell]
symbol = "î· "
format = 'via [$symbol]($style)'
[helm]
symbol = "âˆ "
format = 'via [$symbol]($style)'
[java]
symbol = "î‰– "
format = 'via [$symbol]($style)'
[julia]
symbol = "î˜¤ "
format = 'via [$symbol]($style)'
[kotlin]
format = 'via [$symbol]($style)'
[lua]
symbol = "î˜  "
format = 'via [$symbol]($style)'
[nim]
symbol = "ïš¤ "
format = 'via [$symbol]($style)'
[nix_shell]
symbol = "ï‹œ "
[nodejs]
symbol = "îœ˜ "
format = 'via [$symbol]($style)'
[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'
[package]
symbol = "ï£– "
format = 'via [$symbol]($style)'
[perl]
symbol = "î© "
format = 'via [$symbol]($style)'
[php]
symbol = "î˜ˆ "
format = 'via [$symbol]($style)'
[pulumi]
format = 'via [$symbol$stack]($style)'
[purescript]
format = 'via [$symbol]($style)'
[python]
symbol = "îˆµ "
format = 'via [$symbol]($style)'
[spack]
symbol = "ğŸ…¢ "
format = 'via [$symbol]($style)'
[red]
format = 'via [$symbol]($style)'
[rlang]
format = 'via [$symbol]($style)'
[ruby]
symbol = "îˆ¾ "
format = 'via [$symbol]($style)'
[rust]
symbol = "î¨ "
format = 'via [$symbol]($style)'
[scala]
symbol = "îœ· "
format = 'via [$symbol]($style)'
[swift]
symbol = "ï¯£ "
format = 'via [$symbol]($style)'
[vagrant]
format = 'via [$symbol]($style)'
[vlang]
format = 'via [$symbol]($style)'
[zig]
format = 'via [$symbol]($style)'
